apiVersion: v1
kind: Secret
metadata:
  name: postgre-secrets
type: Opaque
data:
  # DB_USER = cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  # DB_PASSWORD = RXN0b0VzVW5QYXNzd29yZFNlY3JldG8=
  # EstoEsUnPasswordSecreto
  DB_PASSWORD: RXN0b0VzVW5QYXNzd29yZFNlY3JldG8=