apiVersion: v1
kind: ConfigMap
metadata:
  # Este nombre se utiliza para hacer referencia a las variables de este archivo
  name: postgres-config
data:
  DB_NAME: postgres
  DB_HOST: postgres-service
  DB_PORT: "5432"

