version: '3'

services:
  app:
    image: gperez991/teslo-shop:1.1.0
    container_name: nest-app
    # depends_on:
    #   - db
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_VERSION: ${APP_VERSION} 
      STAGE: ${STAGE} 
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_NAME: ${DB_NAME} 
      DB_HOST: ${DB_HOST} 
      DB_PORT: ${DB_PORT} 
      DB_USERNAME: ${DB_USERNAME} 
      PORT: ${PORT} 
      HOST_API: ${HOST_API} 
      JWT_SECRET: ${JWT_SECRET} 

  # db:
  #   image: 'postgres:14.3'
  #   restart: always
  #   ports:
  #     - ${DB_PORT}:${DB_PORT}
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   container_name: ${DB_NAME}
  #   volumes:
  #     - postgresDB:/var/lib/postgresql/data

# volumes:
#   postgresDB:
#     external: false
